name: Build and Push Docker Image

on:
 push: 
    branches: 
      - main

jobs:
  build-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build user_service
        run:
         docker build -t ghcr.io/${{ github.repository }}/user_service:latest ./user_service

      - name: Push user_service
        run: 
         docker push ghcr.io/${{ github.repository }}/user_service:latest
      
